apiVersion: apps/v1
kind: Deployment
metadata:
  name: edureka-purdue
  labels:
    app: edureka-purdue
  namespace: oumar
spec:
  replicas: 6
  selector:
    matchLabels:
      app: edureka-purdue
  template:
    metadata:
      labels:
        app: edureka-purdue
    spec:
      containers:
      - name: edureka-purdue
        image: oumarkenneh/edu-project-reka
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
