---
- hosts: kubernetes
  user: root
  tasks: 

  - name: deploy edureka app
    command: kubectl apply -f /etc/ansible/edureka-deploy.yml
    command: kubectl apply -f /etc/ansible/service.edureka.yml

